version: "3.9"

services:
  ondacast-admin:
    build:
      context: .
      args:
        PUBLIC_MOCK_API: ${PUBLIC_MOCK_API:-0}
        PUBLIC_API_URL: ${PUBLIC_API_URL:-https://api.ondacast.com}
    container_name: ondacast-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - ondacast

networks:
  ondacast:
    external: true
